"""Add missing columns to users table

Revision ID: 27f10c014018
Revises: 
Create Date: 2025-09-27 03:47:23.085651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f10c014018'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('recipient', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('headers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('threat_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('extracted_features', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('model_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('processing_time_ms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('urls_found', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_column('quarantined')

    with op.batch_alter_table('quarantine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sender', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('recipient', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('headers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('threat_indicators', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('prediction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('threat_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('released_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('release_reason', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('quarantine_email_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('email_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('preferences', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('settings', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('settings')
        batch_op.drop_column('preferences')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('role')
        batch_op.drop_column('provider')
        batch_op.drop_column('avatar')
        batch_op.drop_column('google_id')
        batch_op.drop_column('name')

    with op.batch_alter_table('quarantine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('quarantine_email_id_fkey'), 'emails', ['email_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('release_reason')
        batch_op.drop_column('released_at')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('threat_level')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('prediction')
        batch_op.drop_column('threat_indicators')
        batch_op.drop_column('reason')
        batch_op.drop_column('headers')
        batch_op.drop_column('body')
        batch_op.drop_column('subject')
        batch_op.drop_column('recipient')
        batch_op.drop_column('sender')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quarantined', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.alter_column('subject',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('processed_at')
        batch_op.drop_column('urls_found')
        batch_op.drop_column('processing_time_ms')
        batch_op.drop_column('model_version')
        batch_op.drop_column('extracted_features')
        batch_op.drop_column('status')
        batch_op.drop_column('threat_level')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('headers')
        batch_op.drop_column('recipient')
        batch_op.drop_column('sender')

    # ### end Alembic commands ###
